public class Game {
    Player human, bot;
    private int[] botHistory = {0,0,0,0,0,0,0,0,0,0};
    private int[] botRecency = {1,1,1,1,1,1,1,1,1,1};
    private int[] humanHistory = {0,0,0,0,0,0,0,0,0,0};
    private int[] humanRecency = {1,1,1,1,1,1,1,1,1,1};
    private int numOfInputs = 0;
    private boolean humanOut, botOut;
    /**
     * History and Recency
     * History:
     * 10 ints in the array hold the count of the (i+1)th number's frequency in the game (i denotes index)
     * Recency:
     * Recency has a minimum value of 0
     * Whenever an (i+1) number is obtained as an input, the ith input is incremented by 10
     * Otherwise it is degenerated by 5, applying the minimum value condition
     * After every 5 games, all except the most recent one gets a recency boost of 5 points
     * Relative probability is calculated as each i's (history * recency)
     * */
    public Game(Player player1, Player player2) {
        if(player1.isBot) {
            bot = player1;
            human = player2;
        } else {
            bot = player2;
            human = player1;
        }
    }

    /**
     * @TODO:
     * + The tosser
     * + Inputs from the players and managers of the arrays
     * ? Shift arrays to the Player implementations, Human and Bot
     * */
}
