public interface Player {
    /**
     * Frequency and Recency (privates in Human and Bot, which will implement this interface)
     * Frequency:
     * 10 ints in the array hold the count of the (i+1)th number's frequency in the game (i denotes index)
     * Recency:
     * Recency has a minimum value of 0
     * Whenever an (i+1) number is obtained as an input, the ith input is incremented by 10
     * Otherwise it is degenerated by 5, applying the minimum value condition
     * After every 5 games, all except the most recent one gets a recency boost of 5 points
     * Relative probability is calculated as each i's (history * recency)
     * */

    public boolean isBot = false;
    public int getInput();
    public boolean isBatting = false;
    public int[] getFrequency();
    public int[] getRecency();
    public int getUnbiasedInput();

}
